name: Fetch Proxies

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install requests

    - name: Run proxy fetch script
      run: python proxy_generator.py

    - name: Commit and push updated proxies
      run: |
        git config --local user.email "russo20073@gmail.com"
        git config --local user.name "Naarm2006"
        git add proxies.txt
        git commit -m "Update proxies"
        git push
